sentence = input()
cleaned = sentence.strip()
normalized = cleaned.lower().replace(".","")
words = normalized.split()
slug = "-".join(words)
index = normalized.find("python")
uppercase = normalized.upper()
print(f"Cleaned: {cleaned}")
print(f"Normalized: {normalized}")
print(f"Words: {words}")
print(f"Slug: {slug}")
print(f"Uppercase: {uppercase}")
print(f"python index: {index}")